### PR TITLE
fix for #111

### PR DESCRIPTION
**Pull request by xquery**
query sets SPARQLRuleset varargs eg.
```
        tupleQuery.setRulesets(SPARQLRuleset.RDFS_FULL,SPARQLRuleset.DOMAIN);
```

added test to verify

### CODE REVIEW

**Comment by grechaw** [comment]
Why is it setRulesets(Object... ) rather than
 setRulesets(SPARQLRuleset... )
 ?

**Comment by xquery** [comment]
defensive programming ... I keep all java api client calls in the impl and sesame 'clean' ... it means if there are any java api client changes that I just have to maintain in the impl. make sense ?

**Comment by grechaw** [comment]
ah
i see.  i do not agree but i see.

**Comment by grechaw** [comment]
Object is just soooo Objectionable

**Comment by xquery** [comment]
ya but for the record you ok with it ... right ?

**Comment by grechaw** [comment]
yes

**Comment by xquery** [comment]
ta very much

**Pull request merged**
