### PR TITLE
sonar suggestions, minor amends

### PR DESCRIPTION
**Pull request by xquery**
* addresses some sonar suggestions #235 
* force sync() of write cache when performing size query
* minor amends

### CODE REVIEW

**Comment by grechaw** [comment]
Looks like an excellent commit, much cleaner exceptions.   If I'm not mistaken, your change near the bottom for the write cache restores the defaults from before you made it configurable.

**Comment by xquery** [comment]
yes I've since varied them

```
        conn.configureWriteCache(10,500,300);
```

you ok with that ?

**Comment by grechaw** [comment]
How did you arrive at those numbers?  Not as a critique -- I want to duplicate your findings for jena

**Comment by xquery** [comment]
to be clear, the defaults are:

init delay: 100
interval: 750
cache size: 500

Where I choose 100ms for init delay as I think its churlish to tax a fast running operation and 100ms seems to be long enough for any marklogic-sesame application to start from a cold start.

marklogic-sesame runs well with cache sizes between 250-1000 because Model is super fast (can load ~10-20k in 500 ms). 

The write cache will flush if time interval has passed or if we have hit cache size limit. 

I choose a value of 500 for cache size and 750 ms interval after testing a representative range of workloads. These represent more the 'middle' then hyper optimised.

Testing revealed that these default values cover a nice range of work loads. 

All of these values are sensitive to network, memory, etc but these seem like a reasonable set of defaults (after testing).

**Pull request merged**
